### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by mightydread** [riseuplabs/crabgrass-core#373]
Hello.. I am trying to install crabgrass on a debian machine and it just throws an error. I don't know if this error is with bundler or with the crabgrass gemfile.

I ran the command `/usr/local/bin/bundler install` and I expected Bundler to install crabgrass

Instead, what actually happened was this error

Error details
```
    TypeError: no implicit conversion of Array into String
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `directory?'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `block in validate'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `delete_if'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `validate'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:80:in `silence'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:51:in `validate'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:346:in `block in load_gemspec_uncached'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:339:in `load_gemspec_uncached'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:329:in `load_gemspec'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:135:in `block in load_spec_files'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:134:in `each'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:134:in `load_spec_files'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:92:in `local_specs'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:100:in `specs'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:564:in `block in converge_locked_specs'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:546:in `converge_locked_specs'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:192:in `resolve'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:163:in `missing_specs'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:187:in `block in resolve_if_need'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:80:in `silence'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:184:in `resolve_if_need'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/exe/bundler:19:in `block in <top (required)>'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/2.1.0/gems/bundler-1.11.2/exe/bundler:17:in `<top (required)>'
      /usr/local/bin/bundler:23:in `load'
      /usr/local/bin/bundler:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 0) [x86_64-linux-gnu]
    GEM_HOME  /var/lib/gems/2.1.0
    GEM_PATH  /var/lib/gems/2.1.0:/home/master/.gem/ruby/2.1.0:/usr/share/rubygems-integration/2.1.0:/usr/share/rubygems-integration/2.1:/usr/share/rubygems-integration/all
    Git       2.1.4
```

**Comment by azul** [comment]
hi @mightydread 

I remember seeing this before. I think it's a bundler version issue. I thought we had fixed it in the install instructions. I will check.

**Comment by mightydread** [comment]
Thanks.. I am now trying to install using rbenv with the doc from the crabgrass repo and are runing in different issues. On ruby 1.8.7 i cannot install rails because the i18n gem requires a higher ruby version. I'm sorry if I spam this repo but the other one has no issue tracker.

**Comment by azul** [comment]
@mightydread, you're at the right place here i would say... which other repo do you mean?

We don't support ruby 1.8.7 anymore. Are you referring to riseuplabs/crabgrass ? that one is outdated. I should make this very clear on the repo.

**Comment by mightydread** [comment]
Yeah I was referring to the riseuplabs/crabgrass repo. I will start over.

**Comment by mightydread** [comment]
Okay.. I started over and manually applied the fix:
* cloned the repo:
    `git clone https://github.com/riseuplabs/crabgrass-core.git`

* installed dependencies except sphinx which i had to build from source:
    `sudo apt-get install ruby ruby-dev rake mysql-server mysql-client libmysqld-dev git make libssl-dev g++ graphicsmagick`

* installed bundler:
    `sudo gem install bundler`

* ran `bundle install`

* Success!!!

Thanks a lot for the quick fix!

**Comment by azul** [comment]
Cool, @mightydread - thanks for the quick feedback. Closing this issue then. Lemme know if you run into other things.
