### ISSUE TITLE
rake cg:compile_assets aborted

### ISSUE THREAD

**Issue by mightydread** [riseuplabs/crabgrass-core#376]
While trying to deploy crabgrass I get the following:

```
rake cg:compile_assets --trace
rake aborted!
Don't know how to build task 'cg:compile_assets'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

**Comment by azul** [comment]
@mightydread I don't think cg:compile_assets exists as a rake task. Where did you learn about it? Maybe it's an issue with the docs. At least rake -T does not show it for me.

**Comment by mightydread** [comment]
I found it in the documentation.. I checked rake -T and found the equivalent.. Thanks...

**Comment by azul** [comment]
@mightydread ahh.... compile_assets is only used in production mode it seems. Are you trying to deploy for production and not development?

**Comment by mightydread** [comment]
Yes..

**Comment by azul** [comment]
We do not use the rails assets pipeline for css - only for js. Lemme lookup how the css is build.

**Comment by azul** [comment]
@mightydread, please try
```bash
  rake cg:images:update_css
```

**Comment by mightydread** [comment]
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/crabgrass/public/images/../stylesheets/icon_png.css
/var/www/crabgrass/lib/tasks/images.rb:4:in `initialize'
/var/www/crabgrass/lib/tasks/images.rb:4:in `open'
/var/www/crabgrass/lib/tasks/images.rb:4:in `write_file'
/var/www/crabgrass/lib/tasks/images.rb:46:in `block (4 levels) in <top (required)>'
/var/www/crabgrass/lib/tasks/images.rb:45:in `each'
/var/www/crabgrass/lib/tasks/images.rb:45:in `block (3 levels) in <top (required)>'
Tasks: TOP => cg:images:update_css
```

**Comment by mightydread** [comment]
I created the directory.. and it compiled...

**Comment by azul** [comment]
lemme keep this open as a reminder to create the directory in the rake task and to add it to the install instructions.

**Comment by mightydread** [comment]
Awesome!
Now off to configure the rest... :smile:
